import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./ThemeProvider";
import Navbar from "./components/navbar/page";
import { ChakraProvider } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script
            async
            src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9341835843740601"
            crossOrigin="anonymous"
          ></script>
          <script
            dangerouslySetInnerHTML={{
              __html: `
               (adsbygoogle = window.adsbygoogle || []).push({
                   google_ad_client: "ca-pub-9341835843740601",
                   enable_page_level_ads: true
              });
                `,
            }}
          />
      </head>
      <body style={{background:"#020528"}}>
      <ThemeProvider>
      <ChakraProvider>
      <Navbar />
      {children}
      </ChakraProvider>
     
      </ThemeProvider>
      </body>
    </html>
  );
}
